# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SYRFGeospatial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SYRFGeospatial
  pod 'GEOSwift'

  target 'SYRFGeospatialTests' do
    # Pods for testing
  end

end
